server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: paymentService
          uri: http://localhost:8082
          predicates:
            - Path=/payments/**
        - id: BillingProfile
          uri: http://localhost:8083
          predicates:
            - Path=/profiles/**